package io.github.luigidemasi.camelkit.knowledge.indexer.asciidoc;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.asciidoctor.ast.StructuralNode;
import org.asciidoctor.extension.BlockMacroProcessor;
import org.asciidoctor.extension.Name;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * AsciidoctorJ block macro processor for {@code jsonpathTable::} directives.
 *
 * <p>
 * Camel's Antora docs use these macros to render option tables from JSON data files generated by the Camel build. The
 * original macros rely on JavaScript template expressions ({@code util.boldLink(...)}, {@code util.description(value)})
 * that cannot be replicated in Java. Instead, this processor renders simplified but complete table rows using the JSON
 * data directly:
 *
 * <pre>
 * | Name | Description | Default | Type |
 * </pre>
 *
 * <p>
 * For each property node, the following fields are extracted: {@code displayName} (falling back to {@code name}),
 * {@code description}, {@code defaultValue}, and {@code javaType} (falling back to {@code type}).
 */
@Name("jsonpathTable")
public class JsonPathTableMacro extends BlockMacroProcessor {

    private static final Logger LOG = LoggerFactory.getLogger(JsonPathTableMacro.class);

    private final Path examplesDir;

    public JsonPathTableMacro(Path examplesDir) {
        this.examplesDir = examplesDir;
    }

    @Override
    public Object process(StructuralNode parent, String target, Map<String, Object> attributes) {
        try {
            // target is like: example$json/kafka.json
            String jsonRelPath = target;
            if (jsonRelPath.startsWith("example$")) {
                jsonRelPath = jsonRelPath.substring("example$".length());
            }

            // Resolve {shortname} if AsciidoctorJ did not expand it
            if (jsonRelPath.contains("{shortname}")) {
                Object shortname = parent.getDocument().getAttribute("shortname");
                if (shortname != null) {
                    jsonRelPath = jsonRelPath.replace("{shortname}", shortname.toString());
                }
            }

            Path jsonFile = examplesDir.resolve(jsonRelPath);
            if (!Files.exists(jsonFile)) {
                return createBlock(parent, "paragraph",
                        "(options table not available)", attributes);
            }

            String jsonContent = Files.readString(jsonFile);
            JSONObject root = new JSONObject(jsonContent);

            // First positional attribute is the JSONPath query
            String query = (String) attributes.get("1");
            if (query == null) {
                return createBlock(parent, "paragraph", "", attributes);
            }
            query = stripQuotes(query);

            // Strip nodes$ prefix if present — Antora uses "nodes$..." to
            // indicate a JSON path inside the data file
            if (query.startsWith("nodes")) {
                query = query.substring("nodes".length());
            }

            // Ensure the query starts with $ for JsonPathUtil
            if (!query.startsWith("$")) {
                query = "$" + query;
            }

            // Execute query
            Object result = JsonPathUtil.query(root, query);
            if (!(result instanceof List<?> nodes) || nodes.isEmpty()) {
                return createBlock(parent, "paragraph", "", attributes);
            }

            // Build a simple table with property data
            StringBuilder table = new StringBuilder();
            for (Object node : nodes) {
                if (node instanceof JSONObject prop) {
                    String name = JsonPathUtil.extractString(prop, "displayName");
                    if (name.isEmpty()) {
                        name = JsonPathUtil.extractString(prop, "name");
                    }
                    String desc = JsonPathUtil.extractString(prop, "description");
                    String defaultVal = JsonPathUtil.valueAsString(prop.opt("defaultValue"));
                    String type = JsonPathUtil.extractString(prop, "javaType");
                    if (type.isEmpty()) {
                        type = JsonPathUtil.extractString(prop, "type");
                    }
                    // Simplify java type: "java.lang.String" -> "String"
                    if (type.contains(".")) {
                        type = type.substring(type.lastIndexOf('.') + 1);
                    }

                    boolean required = prop.optBoolean("required", false);
                    String reqMarker = required ? " *Required*" : "";

                    table.append(String.format(Locale.ROOT, "| %s%s | %s | %s | %s%n",
                            name, reqMarker, truncate(desc, 200), defaultVal, type));
                }
            }

            // Return as a passthrough block so it's included in the output as-is
            return createBlock(parent, "pass", table.toString(), attributes);

        } catch (Exception e) {
            LOG.warn("  jsonpathTable failed for {}: {}", target, e.getMessage());
            return createBlock(parent, "paragraph", "", attributes);
        }
    }

    private static String stripQuotes(String s) {
        if (s != null && s.length() >= 2) {
            if ((s.startsWith("'") && s.endsWith("'"))
                    || (s.startsWith("\"") && s.endsWith("\""))) {
                return s.substring(1, s.length() - 1);
            }
        }
        return s;
    }

    private static String truncate(String s, int maxLen) {
        if (s == null)
            return "";
        // Remove newlines for table cells
        s = s.replace("\n", " ").replace("\r", "");
        if (s.length() > maxLen)
            return s.substring(0, maxLen) + "...";
        return s;
    }
}
